### ISSUE TITLE
No feeds configured

### ISSUE THREAD

**Issue by Ravenightwing** [joethei/obsidian-rss#57]
A fantastic plugin! But I cannot use it since after configuration it said no feeds configured :( ![Screen Shot 2021-12-21 at 9 57 39 AM](https://user-images.githubusercontent.com/73371424/146857816-c9509450-aa97-4645-9b57-613029c1c837.png)

**Comment by joethei** [comment]
Sorry, I messed something up in the latest version, should be fixed with the next update

**Comment by kyugao** [comment]
meet same error. wait for the fix, thx a lot

**Comment by Ravenightwing** [comment]
> Sorry, I messed something up in the latest version, should be fixed with the next update

Thanks a lot!!!! Merry Christmas!!

**Comment by insecurejezza** [comment]
I'm still experiencing the same issue after the latest release. Tried a fresh install of the plugin and still have the same issue.

**Comment by joethei** [comment]
Could you check if there is anything in the console if you are on desktop(Ctrl/Cmd+Shift+I)?

**Comment by joethei** [comment]
Could you check if this issue still exists in 1.0.1?
This might have been the same issue as #66

**Comment by Ravenightwing** [comment]
> Could you check if this issue still exists in 1.0.1? This might have been the same issue as #66

This issue does not exist! Thanks @joethei 
but now it shows loading without feeds (should I create this in a new issue(?)
![Screen Shot 2022-02-07 at 11 05 07 AM](https://user-images.githubusercontent.com/73371424/152718104-9a304acc-1fc0-44d4-a768-5300e14a1e4a.png)
After I refreshed feeds, the console displays
```
   updating feeds
```
and then
```
    Uncaught (in promise) TypeError: Cannot read property 'undefined' of undefined
    at DataManager.setTotalStats (eval at <anonymous> (app.js:1), <anonymous>:5939:21)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6225:34)
    setTotalStats@manager.ts:100
    eval @ main.ts:66
```
I'm not sure whether it is related to this plugin though
sorry for replying to it so late(

**Comment by Ravenightwing** [comment]
This is what in console when I opened obsidian(
```
Uncaught (in promise) TypeError: Cannot read property 'children' of null
    at e.getSideLeaf (app.js:1)
    at e.getRightLeaf (app.js:1)
    at RssReaderPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:15213:32)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:67:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1), <anonymous>:51:10)
    at RssReaderPlugin.initLeaf (eval at <anonymous> (app.js:1), <anonymous>:15209:12)
    at RssReaderPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:15046:20)
    at Generator.next (<anonymous>)
```

**Comment by Ravenightwing** [comment]
Reopen the plugin would just be fine to solve all probs
